### ISSUE TITLE
Agregar horas a Tarea

### ISSUE THREAD

**Issue by FacuMastri** [NicolasEzequielZulaicaRivera/aninfo_tribu_1_2022_1c#7]
**Como** Empleado, **quiero** agregar horas trabajadas a una tarea, para hacer un seguimiento del desarrollo del proyecto

Criterios de aceptación:
- [ ] **Dado que** hay una tarea abierta, **cuando** selecciono la opcion de finalizar la tarea, **entonces** puedo agregar las horas que duro.
- [ ] **Dado que** finalize una tarea, **cuando** se actualiza correctamente, **entonces** el sistema deberá informar que se actualizo correctamente.
- [ ] **Dado que** finalize una tarea, **cuando** se produce un error, **entonces** el sistema deberá mostrar un mensaje de error.

**Comment by efoppiano** [comment]
No corresponde al módulo de proyectos
